services:
  postgres:
    container_name: postgres_container
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: api_django_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    container_name: api_container
    build: 
      context: ./apps/api
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api:/app
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
