# Generated by Django 5.1.6 on 2025-03-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    DML = """
        INSERT INTO menu_category (created_at, updated_at, active, category) VALUES 
            (now(), now(), True, 'Desayuno'),
            (now(), now(), True, 'Almnuerzo'),
            (now(), now(), True, 'Cena'),
            (now(), now(), True, 'Postres'),
            (now(), now(), True, 'Bebidas'),
            (now(), now(), True, 'Cafetería');
    """

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(DML, reverse_sql=migrations.RunSQL.noop),
    ]
